
local M = {}

M.TIMER_IMPL = {
	HASHED_WHEEL = 1, -- 单层时间轮
	HEAP_QUEUE = 2,
	SEQUENCE = 3,
	SIMPLE = 4,
	TIMING_WHEEL = 5, -- 多层时间轮
}

M.TIMER_KEY_NEXT_TS = 1
M.TIMER_KEY_SEQ = 2
M.TIMER_KEY_INTERVAL = 3
M.TIMER_KEY_FUNC = 4

M.TIMER_TAG_USER = 0x1
M.TIMER_TAG_REPEAT = 0x2
M.TIMER_TYPE_SHIFT = 2
M.TIMER_SESSION_MAX = (1 << 60) - 1

return M